services:
  mongodb:
    image: mongo:7.0
    ports:
      - "27019:27017" # 27019 is on host
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:  
      MONGODB_URL: mongodb://admin:password@mongodb:27017/
      MONGODB_DB_NAME: metadata_db
      HTTP_VERIFY_SSL: "false"
    depends_on:
      mongodb:
        condition: service_healthy

  tests:
    build: .
    command: pytest -v
    environment:
      MONGODB_URL: mongodb://admin:password@mongodb:27017/
      MONGODB_DB_NAME: metadata_db
      HTTP_VERIFY_SSL: "false"
    depends_on:
      mongodb:
        condition: service_healthy
    profiles:
      - test